In [1]:
#| default_exp tensor

In [2]:
from typing import TypeVar
import numpy as np
import matplotlib
from graphviz import Digraph
import torch

In [3]:

TTensor = TypeVar("TTensor", bound="Tensor")

class Tensor:
    
    def __init__(self, data:list, _prev:set=(), _op: str='', label='') -> None:
        self.data = np.array(data)
        self._prev = _prev
        self._op = _op
        self.label = label
        
    def __repr__(self) -> str:        
        return f"Value(data={np.array_str(self.data)}, _op={self._op}, label={self.label}"
    
    def __add__(self, other: TTensor) -> TTensor:
       res = Tensor(self.data + other.data, _op='+', _prev=(self, other))
       return res  
       
    def __mul__(self, other: TTensor) -> TTensor:
        return Tensor(self.data * other.data, _op='*', _prev=(self, other))
        
    def __matmul__(self, other: TTensor) -> TTensor:
        return Tensor(self.data @ other.data, _op='@', _prev=(self, other))
    
    def __pow__(self, other: TTensor) -> TTensor:
        return Tensor(self.data ** other.data, _op='**', _prev=(self, other)) 
    
    def __truediv__(self, other: TTensor) -> TTensor:
        # /
        ...
        
    def __rmul__(self, other: TTensor) -> TTensor: # other * self
        return self * other

    def __truediv__(self, other: TTensor) -> TTensor: # self / other
        return self * other**-1

    def __neg__(self): # -self
        return self * -1

    def __sub__(self: TTensor) -> TTensor: # self - other
        return self + (-other)

    def __radd__(self, other: TTensor) -> TTensor: # other + self
        return self + other        
        

A = Tensor([[1.,2.,3.],[4.,5.,6.]])
B = Tensor([1.,2.,3.])
C = (A @ B)
D=C**Tensor(2)
C


Value(data=[14. 32.], _op=@, label=

In [4]:
At = torch.tensor([[1.,2.,3.],[4.,5.,6.]], requires_grad=True)
Bt = torch.tensor([[1.,1.],[2.,2.],[3.,3.]], requires_grad=True)

Ct=At@Bt
Ct.retain_grad()
#Ct.backward()
St = Ct.sum()
St.retain_grad()
St.backward()
St.grad, At.grad, Bt.grad, Ct.grad



(tensor(1.),
 tensor([[2., 4., 6.],
         [2., 4., 6.]]),
 tensor([[5., 5.],
         [7., 7.],
         [9., 9.]]),
 tensor([[1., 1.],
         [1., 1.]]))

In [5]:
x1 = torch.Tensor([2.0]).double()                ; x1.requires_grad = True
x2 = torch.Tensor([0.0]).double()                ; x2.requires_grad = True
w1 = torch.Tensor([-3.0]).double()               ; w1.requires_grad = True
w2 = torch.Tensor([1.0]).double()                ; w2.requires_grad = True
b = torch.Tensor([6.8813735870195432]).double()  ; b.requires_grad = True
n = x1*w1 + x2*w2 + b
o = torch.tanh(n)

#print(o.data.item())
o.backward()

print('---')
print('x2', x2.grad.item())
print('w2', w2.grad.item())
print('x1', x1.grad.item())
print('w1', w1.grad.item())

---
x2 0.5000001283844369
w2 0.0
x1 -1.5000003851533106
w1 1.0000002567688737
